# Generated by Django 4.0.3 on 2022-06-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='items',
        ),
    ]
