# Generated by Django 4.0.3 on 2022-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=5000)),
                ('status', models.BooleanField(default=False)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
