# Generated by Django 4.0.3 on 2022-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='availability_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_time', models.DateTimeField()),
                ('availability_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.TextField()),
                ('link', models.CharField(max_length=600)),
                ('about', models.CharField(max_length=1000)),
                ('price', models.TextField()),
                ('vendor_id', models.CharField(max_length=10)),
                ('reserved', models.BooleanField(default=False)),
                ('rate', models.TextField(max_length=10)),
                ('amenities', models.ManyToManyField(to='Items.amenities')),
                ('availability_date', models.ManyToManyField(to='Items.availability_date')),
                ('images', models.ManyToManyField(to='Items.images')),
                ('types', models.ManyToManyField(to='Items.itemtype')),
            ],
        ),
    ]
