# Generated by Django 4.0.3 on 2022-06-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_items'),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability_date',
            old_name='availability_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='availability_date',
            old_name='availability_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='availability_date',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reserved',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=100, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='resevedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.availability_date')),
            ],
        ),
    ]
