# Generated by Django 4.0.3 on 2022-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='event',
            new_name='event_id',
        ),
    ]
